# **NUMPY**

**Array Creation**

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3])
arr
zero=np.zeros((3,3))
one = np.ones((3,3))
eye=np.eye(3,dtype=int)
full =np.full((3,3),9)
emp=np.empty((3,3))
ident=np.identity(3)
ran =np.random.random((3,3))
randn = np.random.randn(3,3)
nandi = np.random.randint(1,10,(3,3))


In [ ]:
zero


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
one


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
eye


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
full


array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [ ]:
emp


array([[6.60886699e-316, 0.00000000e+000, 6.51881132e-310],
       [6.51880439e-310, 5.33423706e-317, 6.51881092e-310],
       [6.51881132e-310, 6.51886555e-310, 3.95252517e-322]])

In [ ]:
ident


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
ran


array([[0.42583156, 0.98506321, 0.09546573],
       [0.79028325, 0.87670419, 0.47111279],
       [0.52967827, 0.04221357, 0.20253294]])

In [ ]:
randn


array([[ 0.27043196,  0.11273401, -0.23596022],
       [ 0.78925288, -0.39469785,  1.14003514],
       [-0.2609157 , -2.40536417, -0.94981349]])

# **Array Info**

In [ ]:
a = [[1,2,3],[2,3,4],[4,5,6]]

In [ ]:
dim = np.ndim(a)
dim

2

In [ ]:
shape = np.shape(a)
shape

(3, 3)

In [ ]:
size = np.size(a)
size

9

In [ ]:
b=np.array(a)
itemsize = b.itemsize
itemsize

8

# **Array Reshaping**

In [ ]:
transpose = np.transpose(a)
transpose

array([[1, 2, 4],
       [2, 3, 5],
       [3, 4, 6]])

In [ ]:
rshape = np.reshape(a,(1,9))
rshape

array([[1, 2, 3, 2, 3, 4, 4, 5, 6]])

In [ ]:
resize= np.resize(a,(1,9))
resize

array([[1, 2, 3, 2, 3, 4, 4, 5, 6]])

In [ ]:
flat = np.array(a).flatten()
flat

array([1, 2, 3, 2, 3, 4, 4, 5, 6])

In [ ]:
ravel = np.array(a).ravel()
ravel

array([1, 2, 3, 2, 3, 4, 4, 5, 6])

# **Math Operations**

In [ ]:
sum = np.sum(a)
sum

np.int64(30)

In [ ]:
sub = np.subtract(a,b)
sub

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
mul = np.multiply(a,b)
mul

array([[ 1,  4,  9],
       [ 4,  9, 16],
       [16, 25, 36]])

In [ ]:
div = np.divide(a,b)
div

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# **Indexing**

In [ ]:
a = np.array([10, 20, 30, 40])
print(a[2])


30


In [ ]:
print(a[1:3])

[20 30]


In [ ]:
x = np.array([1, 2, 3, 4])
print(np.where(x > 2))


(array([2, 3]),)


In [ ]:
print(np.argmax(x))
print(np.argmin(x))

3
0


In [ ]:
a = np.array([50, 10, 30])
print(np.argsort(a))

[1 2 0]


In [ ]:
np.array([3, 1, 2])
print(np.sort(a))

[1 2 3]


In [ ]:
a = np.array([1, 1, 2, 3, 2])
print(np.unique(a))  # [1 2 3]


[1 2 3]


In [ ]:
print(np.in1d([1, 2], [1, 3]))


[ True False]


/tmp/ipython-input-77-3225201706.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d([1, 2], [1, 3]))


In [ ]:
a = np.array([0, 1, 0, 2])
print(np.nonzero(a))

(array([1, 3]),)


# **Copy/Save/Load**

In [ ]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a, b)


[1 2 3] [100   2   3]


In [ ]:
np.save('my_array', a)
loaded = np.load('my_array.npy')
print(loaded)


[1 2 3]


# **Matrix Operation**

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.matmul(a, b))


[[19 22]
 [43 50]]


In [ ]:
from numpy.linalg import inv
a = np.array([[1, 2], [3, 4]])
print(inv(a))


[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
from numpy.linalg import det
print(det(a))


-2.0000000000000004


In [ ]:
print(np.trace(a))


5


# **Pandas**

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('ml_pandas_practice.csv')

# ***Data Inspection***

In [ ]:
df.head()

ID     Name   Age Gender Department JoiningDate   Salary  Rating  \
0   1    Alice  25.0      F         HR  2021-01-15  50000.0     4.5   
1   2      Bob  30.0      M         IT  2020-07-23  60000.0     3.8   
2   3  Charlie   NaN      M         IT  2022-03-01  55000.0     4.2   
3   4    David  22.0      M    Finance  2021-08-10  58000.0     3.9   
4   5      Eva  28.0      F         HR  2019-12-01      NaN     4.0   

  PromotionEligible  RemoteWorker  
0               Yes          True  
1                No         False  
2               Yes          True  
3                No         False  
4               Yes          True

In [ ]:
df.tail()

ID     Name   Age Gender Department JoiningDate   Salary  Rating  \
0   1    Alice  25.0      F         HR  2021-01-15  50000.0     4.5   
1   2      Bob  30.0      M         IT  2020-07-23  60000.0     3.8   
2   3  Charlie   NaN      M         IT  2022-03-01  55000.0     4.2   
3   4    David  22.0      M    Finance  2021-08-10  58000.0     3.9   
4   5      Eva  28.0      F         HR  2019-12-01      NaN     4.0   

  PromotionEligible  RemoteWorker  
0               Yes          True  
1                No         False  
2               Yes          True  
3                No         False  
4               Yes          True

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   ID                 5 non-null      int64  
 1   Name               5 non-null      object 
 2   Age                4 non-null      float64
 3   Gender             5 non-null      object 
 4   Department         5 non-null      object 
 5   JoiningDate        5 non-null      object 
 6   Salary             4 non-null      float64
 7   Rating             5 non-null      float64
 8   PromotionEligible  5 non-null      object 
 9   RemoteWorker       5 non-null      bool   
dtypes: bool(1), float64(3), int64(1), object(5)
memory usage: 497.0+ bytes


In [ ]:
df.describe()

ID    Age       Salary    Rating
count  5.000000   4.00      4.00000  5.000000
mean   3.000000  26.25  55750.00000  4.080000
std    1.581139   3.50   4349.32945  0.277489
min    1.000000  22.00  50000.00000  3.800000
25%    2.000000  24.25  53750.00000  3.900000
50%    3.000000  26.50  56500.00000  4.000000
75%    4.000000  28.50  58500.00000  4.200000
max    5.000000  30.00  60000.00000  4.500000

In [ ]:
df.shape

(5, 10)

In [ ]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
df.dtypes

ID                     int64
Name                  object
Age                  float64
Gender                object
Department            object
JoiningDate           object
Salary               float64
Rating               float64
PromotionEligible     object
RemoteWorker            bool
dtype: object

In [ ]:
df.columns

Index(['ID', 'Name', 'Age', 'Gender', 'Department', 'JoiningDate', 'Salary',
       'Rating', 'PromotionEligible', 'RemoteWorker'],
      dtype='object')

***Data cleaning***

In [ ]:
df


ID     Name   Age Gender Department JoiningDate   Salary  Rating  \
0   1    Alice  25.0      F         HR  2021-01-15  50000.0     4.5   
1   2      Bob  30.0      M         IT  2020-07-23  60000.0     3.8   
2   3  Charlie   NaN      M         IT  2022-03-01  55000.0     4.2   
3   4    David  22.0      M    Finance  2021-08-10  58000.0     3.9   
4   5      Eva  28.0      F         HR  2019-12-01      NaN     4.0   

  PromotionEligible  RemoteWorker  
0               Yes          True  
1                No         False  
2               Yes          True  
3                No         False  
4               Yes          True

In [ ]:
df.drop(1,axis=0) #axis=1 --->column
#axis = 0----->row

ID     Name   Age Gender Department JoiningDate   Salary  Rating  \
0   1    Alice  25.0      F         HR  2021-01-15  50000.0     4.5   
2   3  Charlie   NaN      M         IT  2022-03-01  55000.0     4.2   
3   4    David  22.0      M    Finance  2021-08-10  58000.0     3.9   
4   5      Eva  28.0      F         HR  2019-12-01      NaN     4.0   

  PromotionEligible  RemoteWorker  
0               Yes          True  
2               Yes          True  
3                No         False  
4               Yes          True

In [ ]:
df.replace(25.0,35.0)

ID     Name   Age Gender Department JoiningDate   Salary  Rating  \
0   1    Alice  35.0      F         HR  2021-01-15  50000.0     4.5   
1   2      Bob  30.0      M         IT  2020-07-23  60000.0     3.8   
2   3  Charlie   NaN      M         IT  2022-03-01  55000.0     4.2   
3   4    David  22.0      M    Finance  2021-08-10  58000.0     3.9   
4   5      Eva  28.0      F         HR  2019-12-01      NaN     4.0   

  PromotionEligible  RemoteWorker  
0               Yes          True  
1                No         False  
2               Yes          True  
3                No         False  
4               Yes          True

In [ ]:
df['Age'].fillna(df['Age'].mean(),inplace=True)  #True means it will also change in original dataframe
df

/tmp/ipython-input-98-2903513124.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)  #True means it will also change in original dataframe


ID     Name    Age Gender Department JoiningDate   Salary  Rating  \
0   1    Alice  25.00      F         HR  2021-01-15  50000.0     4.5   
1   2      Bob  30.00      M         IT  2020-07-23  60000.0     3.8   
2   3  Charlie  26.25      M         IT  2022-03-01  55000.0     4.2   
3   4    David  22.00      M    Finance  2021-08-10  58000.0     3.9   
4   5      Eva  28.00      F         HR  2019-12-01      NaN     4.0   

  PromotionEligible  RemoteWorker  
0               Yes          True  
1                No         False  
2               Yes          True  
3                No         False  
4               Yes          True

In [ ]:
df.astype({'Age':'int'})

ID     Name  Age Gender Department JoiningDate   Salary  Rating  \
0   1    Alice   25      F         HR  2021-01-15  50000.0     4.5   
1   2      Bob   30      M         IT  2020-07-23  60000.0     3.8   
2   3  Charlie   26      M         IT  2022-03-01  55000.0     4.2   
3   4    David   22      M    Finance  2021-08-10  58000.0     3.9   
4   5      Eva   28      F         HR  2019-12-01      NaN     4.0   

  PromotionEligible  RemoteWorker  
0               Yes          True  
1                No         False  
2               Yes          True  
3                No         False  
4               Yes          True

# ***Handling Missing values***

In [ ]:
df['Salary'].interpolate(method='linear',direction='forward')

0    50000.0
1    60000.0
2    55000.0
3    58000.0
4    58000.0
Name: Salary, dtype: float64

In [ ]:
df.isnull()

ID   Name    Age  Gender  Department  JoiningDate  Salary  Rating  \
0  False  False  False   False       False        False   False   False   
1  False  False  False   False       False        False   False   False   
2  False  False  False   False       False        False   False   False   
3  False  False  False   False       False        False   False   False   
4  False  False  False   False       False        False    True   False   

   PromotionEligible  RemoteWorker  
0              False         False  
1              False         False  
2              False         False  
3              False         False  
4              False         False

In [ ]:
df.notnull()

ID  Name   Age  Gender  Department  JoiningDate  Salary  Rating  \
0  True  True  True    True        True         True    True    True   
1  True  True  True    True        True         True    True    True   
2  True  True  True    True        True         True    True    True   
3  True  True  True    True        True         True    True    True   
4  True  True  True    True        True         True   False    True   

   PromotionEligible  RemoteWorker  
0               True          True  
1               True          True  
2               True          True  
3               True          True  
4               True          True

In [ ]:
df.interpolate(method='linear',direction='backward',inplace=True)
df

/tmp/ipython-input-103-4267119695.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='linear',direction='backward',inplace=True)


ID     Name    Age Gender Department JoiningDate   Salary  Rating  \
0   1    Alice  25.00      F         HR  2021-01-15  50000.0     4.5   
1   2      Bob  30.00      M         IT  2020-07-23  60000.0     3.8   
2   3  Charlie  26.25      M         IT  2022-03-01  55000.0     4.2   
3   4    David  22.00      M    Finance  2021-08-10  58000.0     3.9   
4   5      Eva  28.00      F         HR  2019-12-01  58000.0     4.0   

  PromotionEligible  RemoteWorker  
0               Yes          True  
1                No         False  
2               Yes          True  
3                No         False  
4               Yes          True

***Data Filtering***

In [ ]:
df.loc[0]

ID                            1
Name                      Alice
Age                        25.0
Gender                        F
Department                   HR
JoiningDate          2021-01-15
Salary                  50000.0
Rating                      4.5
PromotionEligible           Yes
RemoteWorker               True
Name: 0, dtype: object

In [ ]:
df.iloc[0]

ID                            1
Name                      Alice
Age                        25.0
Gender                        F
Department                   HR
JoiningDate          2021-01-15
Salary                  50000.0
Rating                      4.5
PromotionEligible           Yes
RemoteWorker               True
Name: 0, dtype: object

In [ ]:
df.at[0, 'Age']

np.float64(25.0)

In [ ]:
df.iat[0, 2]

np.float64(25.0)

In [ ]:
df['Age']>25

0    False
1     True
2     True
3    False
4     True
Name: Age, dtype: bool

In [ ]:
df.query('Age>25')

ID     Name    Age Gender Department JoiningDate   Salary  Rating  \
1   2      Bob  30.00      M         IT  2020-07-23  60000.0     3.8   
2   3  Charlie  26.25      M         IT  2022-03-01  55000.0     4.2   
4   5      Eva  28.00      F         HR  2019-12-01  58000.0     4.0   

  PromotionEligible  RemoteWorker  
1                No         False  
2               Yes          True  
4               Yes          True

In [ ]:
df[df['Age'].isin([28,30])]

ID Name   Age Gender Department JoiningDate   Salary  Rating  \
1   2  Bob  30.0      M         IT  2020-07-23  60000.0     3.8   
4   5  Eva  28.0      F         HR  2019-12-01  58000.0     4.0   

  PromotionEligible  RemoteWorker  
1                No         False  
4               Yes          True

# ***Data Transformation***

In [ ]:
df.round(1) #round off upto 1 digit

ID     Name   Age Gender Department JoiningDate   Salary  Rating  \
0   1    Alice  25.0      F         HR  2021-01-15  50000.0     4.5   
1   2      Bob  30.0      M         IT  2020-07-23  60000.0     3.8   
2   3  Charlie  26.2      M         IT  2022-03-01  55000.0     4.2   
3   4    David  22.0      M    Finance  2021-08-10  58000.0     3.9   
4   5      Eva  28.0      F         HR  2019-12-01  58000.0     4.0   

  PromotionEligible  RemoteWorker  
0               Yes          True  
1                No         False  
2               Yes          True  
3                No         False  
4               Yes          True

In [ ]:
df['Age'].clip(25,30)

0    25.00
1    30.00
2    26.25
3    25.00
4    28.00
Name: Age, dtype: float64

In [ ]:
df['Salary'].map({58000.0:60000.0})

0        NaN
1        NaN
2        NaN
3    60000.0
4    60000.0
Name: Salary, dtype: float64